### ISSUE TITLE
failing to install lodash

### ISSUE THREAD

**Issue by apolishch** [half-pipe/half-pipe#47] opened 2013-10-04 01:49 UTC
npm info install node-minify@0.6.1
npm info postinstall node-minify@0.6.1
npm verb about to build /Users/abe/github/togo/node_modules/grunt-requirejs/node_modules/grunt-lodashbuilder
npm info build /Users/abe/github/togo/node_modules/grunt-requirejs/node_modules/grunt-lodashbuilder
npm verb linkStuff [ false,
npm verb linkStuff   false,
npm verb linkStuff   false,
npm verb linkStuff   '/Users/abe/github/togo/node_modules/grunt-requirejs/node_modules' ]
npm info linkStuff grunt-lodashbuilder@0.1.7
npm verb linkBins grunt-lodashbuilder@0.1.7
npm verb linkMans grunt-lodashbuilder@0.1.7
npm verb rebuildBundles grunt-lodashbuilder@0.1.7
npm verb rebuildBundles [ '.bin',
npm verb rebuildBundles   'grunt-contrib-jshint',
npm verb rebuildBundles   'grunt-contrib-nodeunit',
npm verb rebuildBundles   'grunt-contrib-watch',
npm verb rebuildBundles   'lodash',
npm verb rebuildBundles   'node-minify',
npm verb rebuildBundles   'semver',
npm verb rebuildBundles   'uglify-js',
npm verb rebuildBundles   'wrench' ]
npm info install grunt-lodashbuilder@0.1.7
npm info postinstall grunt-lodashbuilder@0.1.7
npm verb unsafe-perm in lifecycle true

> grunt-lodashbuilder@0.1.7 postinstall /Users/abe/github/togo/node_modules/grunt-requirejs/node_modules/grunt-lodashbuilder
> node ./bin/post-install.js

module.js:340
    throw err;
          ^
Error: Cannot find module '../node_modules/lodash/vendor/tar/tar.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /Users/abe/github/togo/node_modules/grunt-requirejs/node_modules/grunt-lodashbuilder/bin/post-install.js:14:13
    at Object.<anonymous> (/Users/abe/github/togo/node_modules/grunt-requirejs/node_modules/grunt-lodashbuilder/bin/post-install.js:166:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
npm info grunt-lodashbuilder@0.1.7 Failed to exec postinstall script
npm info /Users/abe/github/togo/node_modules/grunt-requirejs/node_modules/grunt-lodashbuilder unbuild
npm info preuninstall grunt-lodashbuilder@0.1.7
npm info uninstall grunt-lodashbuilder@0.1.7
npm verb false,/Users/abe/github/togo/node_modules,/Users/abe/github/togo/node_modules/grunt-requirejs/node_modules unbuild grunt-lodashbuilder@0.1.7
npm info postuninstall grunt-lodashbuilder@0.1.7
npm verb about to build /Users/abe/github/togo/node_modules/grunt-requirejs
npm info /Users/abe/github/togo/node_modules/grunt-requirejs unbuild
npm info preuninstall grunt-requirejs@0.3.5
npm info uninstall grunt-requirejs@0.3.5
npm verb true,/Users/abe/github/togo/node_modules,/Users/abe/github/togo/node_modules unbuild grunt-requirejs@0.3.5
npm info postuninstall grunt-requirejs@0.3.5
npm ERR! weird error 8
npm verb exit [ 1, true ]
npm verb about to build /Users/abe/github/togo/node_modules/grunt-requirejs/node_modules/grunt-jquerybuilder
npm info /Users/abe/github/togo/node_modules/grunt-requirejs/node_modules/grunt-jquerybuilder unbuild
npm info preuninstall grunt-jquerybuilder@0.1.4
npm info uninstall grunt-jquerybuilder@0.1.4
npm verb false,/Users/abe/github/togo/node_modules,/Users/abe/github/togo/node_modules/grunt-requirejs/node_modules unbuild grunt-jquerybuilder@0.1.4
npm verb /Users/abe/github/togo/node_modules/grunt-requirejs/node_modules/.bin,[object Object] binRoot
npm info postuninstall grunt-jquerybuilder@0.1.4
npm ERR! not ok code 0

Abes-MacBook-Pro:togo abe$ node -v
v0.10.20
Abes-MacBook-Pro:togo abe$ npm -v
1.3.11

It seems that this bug was reported (and fixed) by grunt-lodash here: 
https://github.com/lodash/grunt-lodash/issues/1

**Comment by barroyo** [comment] 2013-10-04 16:55
I am also facing this issue, same version as @apolishch but in a ubuntu server.

**Comment by joefiorini** [comment] 2013-10-06 02:46
I appreciate you both posting on this. The problem is that the 0.2 release of half-pipe uses an old version (0.3.x) of grunt-requirejs. You can update that to 0.4.0 in your package.json. Or you can try updating half-pipe to 0.3.0.alpha. I'm still working on documentation for it, I'll try to push an update to the README soon.

**Comment by barroyo** [comment] 2013-10-10 13:33
It worked changing to 0.4, thanks!

**Comment by joefiorini** [comment] 2013-10-10 14:00
Great! Thanks for following up. Closing.

**Closed as completed by joefiorini** 2013-10-10 14:00 UTC
